apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: linter
  annotations:
    "lighthouse.jenkins-x.io/prependStepsURL": "https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/master/tasks/git-clone/git-clone-pr.yaml"
spec:
  stepTemplate:
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
    workingDir: /workspace/source
  steps:
    - script: |
        #!/usr/bin/env bash
        export DEFAULT_WORKSPACE="."
        export DISABLE_ERRORS="true"
        export OUTPUT_DETAILS="detailed"
        export OUTPUT_FORMAT="tap"
        export RUN_LOCAL="true"
        export VALIDATE_ALL_CODEBASE="true"
        /action/lib/linter.sh
      image: github/super-linter:v3.13.1
      name: lint
    - script: |
        #!/usr/bin/env bash
        jx-tap tap -d super-linter.report
      image: gcr.io/jenkinsxio/jx-tap:latest
      name: pr-comment
