apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: linter
  annotations:
    lighthouse.jenkins-x.io/loadFileRefs: ".*"
spec:
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone/git-clone-pr
  - name: lint
    taskSpec:
      steps:
      - script: |
          #!/usr/bin/env bash
          export DEFAULT_WORKSPACE="."
          export DISABLE_ERRORS="true"
          export OUTPUT_DETAILS="detailed"
          export OUTPUT_FORMAT="tap"
          export RUN_LOCAL="true"
          export VALIDATE_ALL_CODEBASE="true"

          ln -s /workspace/source /tmp/lint
          cd /tmp/lint
          mkdir -p super-linter.report
          /action/lib/linter.sh
        image: github/super-linter:latest
        name: lint
        resources:
          requests:
            cpu: 400m
            memory: 512Mi
        workingDir: /workspace/source
      - script: |
          #!/usr/bin/env bash
          jx-tap tap -d super-linter.report
        image: gcr.io/jenkinsxio/jx-tap:latest
        name: pr-comment
        resources:
          requests:
            cpu: 400m
            memory: 512Mi
        workingDir: /workspace/source
