apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: linter
spec:
  stepTemplate:
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
    volumeMounts:
      - mountPath: /home/jenkins
        name: workspace-volume
      - mountPath: /etc/podinfo
        name: podinfo
        readOnly: true
    workingDir: /workspace/source
  steps:
    - script: |
        #!/usr/bin/env bash
        # allow the git clone source diretory to be configured in via an environment variable
        export SUBDIR="${WORKSPACE_SOURCE_DIR:-source}"
        echo "git cloning url: $REPO_URL version $PULL_PULL_SHA to dir: $SUBDIR"
        mkdir -p $HOME
        git config --global --add user.name ${GIT_AUTHOR_NAME:-jenkins-x-bot}
        git config --global --add user.email ${GIT_AUTHOR_EMAIL:-jenkins-x@googlegroups.com}
        git config --global credential.helper store
        git clone $REPO_URL $SUBDIR
        cd $SUBDIR
        git checkout $PULL_PULL_SHA
        echo "checked out revision: $PULL_PULL_SHA to dir: $SUBDIR"
      image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
      name: git-clone
      resources: { }
      workingDir: /workspace
    - args:
        - '[ -d /builder/home ] || mkdir -p /builder && ln -s /tekton/home /builder/home'
      command:
        - /bin/sh
        - -c
      image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
      name: setup-builder-home
      resources: { }
    - args:
        - step
        - git
        - merge
        - --verbose
        - --baseSHA
        - $(params.PULL_BASE_SHA)
        - --sha
        - $(params.PULL_PULL_SHA)
        - --baseBranch
        - $(params.PULL_BASE_REF)
      command:
        - jx
      image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
      name: git-merge
      resources: { }
    - script: |
        #!/usr/bin/env bash
        export DEFAULT_WORKSPACE="."
        export DISABLE_ERRORS="true"
        export OUTPUT_DETAILS="detailed"
        export OUTPUT_FORMAT="tap"
        export RUN_LOCAL="true"
        export VALIDATE_ALL_CODEBASE="true"

        ln -s /workspace/source /tmp/lint
        cd /tmp/lint
        mkdir -p super-linter.report
        /action/lib/linter.sh
      image: github/super-linter:latest
      name: lint
      resources: { }
    - script: |
        #!/usr/bin/env bash
        jx-tap tap -d super-linter.report
      image: gcr.io/jenkinsxio/jx-tap:latest
      name: pr-comment
      resources: { }
  volumes:
    - emptyDir: { }
      name: workspace-volume
    - downwardAPI:
        items:
          - fieldRef:
              fieldPath: metadata.labels
            path: labels
      name: podinfo
