apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: lint
    context: "lint"
    always_run: true
    optional: false
    trigger: "/lint"
    rerun_command: "/relint"
    source: "lint.yaml"
  - name: bad
    context: "bad"
    always_run: true
    optional: false
    trigger: "/bad"
    rerun_command: "/relint"
    source: "bad3.yaml"
